ksm30825/travelInterface

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/penalty/controller/PenaltyController.java
src/main/webapp/WEB-INF/config/myRequest-servlet.xml
src/main/webapp/WEB-INF/views/common/myPageHeader.jsp
src/main/webapp/WEB-INF/views/inquiry/goInquiry.jsp
src/main/webapp/WEB-INF/views/inquiry/myInquiryDetail.jsp
src/main/webapp/WEB-INF/views/inquiry/myInquiryList.jsp
src/main/webapp/WEB-INF/views/travelRequest/myRequestList.jsp
src/main/webapp/WEB-INF/views/travelRequest/myRequestPlan.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestPlan.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestStart.jsp
src/main/webapp/WEB-INF/views/travelRequest/travelRequest.jsp

뷰 페이지 연결/지도 띄우기

---

src/main/webapp/WEB-INF/views/travelRequest/requestStart.jsp

지역 검색/맵찍어서 마커찍기/마커 두개이상일때 경로 연결 성공!!

---

src/main/java/com/kh/ti/statistics/controller/StatisticsController.java
src/main/java/com/kh/ti/travelBoard/controller/TravelBoardController.java
src/main/webapp/WEB-INF/config/statistics-servlet.xml
src/main/webapp/WEB-INF/views/admin/statistics/adminGenderStatistics.jsp
src/main/webapp/WEB-INF/views/admin/statistics/adminStatisticsNav.jsp
src/main/webapp/WEB-INF/views/common/adminMainNav.jsp
src/main/webapp/WEB-INF/views/common/myPageHeader.jsp
src/main/webapp/WEB-INF/views/travelBoard/myBuyTravelList.jsp
src/main/webapp/WEB-INF/views/travelBoard/travelDetailSubNav.jsp
src/main/webapp/WEB-INF/views/travelBoard/travelDetailSubReview.jsp
src/main/webapp/WEB-INF/views/travelBoard/travelList.jsp
src/main/webapp/WEB-INF/views/travelBoard/travelSearchBar.jsp
src/main/webapp/WEB-INF/web.xml

예랑 - 여행일정 뷰, 마이페이지/구매한일정 뷰, 관리자페이지 통계 뷰, 통계관련 서블릿 생성(web.xml파일에 내용 추가함),

---

src/main/webapp/WEB-INF/views/travelRequest/requestStart.jsp

경로 연결 기능 수정

---

src/main/webapp/WEB-INF/views/travel/detailEditor.jsp
src/main/webapp/WEB-INF/views/travel/scheduleEditor.jsp
src/main/webapp/WEB-INF/views/travel/travelEditor.jsp
src/main/webapp/resources/js/travel/travel.js

(민) travel뷰 수정

---

pom.xml
src/main/java/com/kh/ti/travelRequest/controller/TravelRequestController.java
src/main/java/com/kh/ti/travelRequest/model/dao/TravelRequestDao.java
src/main/java/com/kh/ti/travelRequest/model/dao/TravelRequestDaoImpl.java
src/main/java/com/kh/ti/travelRequest/model/service/TravelRequestService.java
src/main/java/com/kh/ti/travelRequest/model/service/TravelRequestServiceImpl.java
src/main/java/com/kh/ti/travelRequest/model/vo/TravelRequest.java
src/main/resources/mybatis-config.xml
src/main/resources/root-context.xml
src/main/webapp/WEB-INF/config/travelRequest-servlet.xml
src/main/webapp/WEB-INF/views/panelty/paneltyDetail.jsp
src/main/webapp/WEB-INF/views/panelty/paneltyList.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestDetail.jsp
src/main/webapp/WEB-INF/views/travelRequest/travelRequest.jsp

여행 의뢰하기 기능 구현/pom,root AOP트랜잭션처리 설정/mybatis-servlet.xml 맵핑 추가

여행 의뢰하기 기능 구현/pom,root-xml AOP트랜잭션처리 설정

---

src/main/java/com/kh/ti/common/PageInfo.java
src/main/java/com/kh/ti/travelRequest/controller/TravelRequestController.java
src/main/java/com/kh/ti/travelRequest/model/dao/TravelRequestDao.java
src/main/java/com/kh/ti/travelRequest/model/dao/TravelRequestDaoImpl.java
src/main/java/com/kh/ti/travelRequest/model/service/TravelRequestService.java
src/main/java/com/kh/ti/travelRequest/model/service/TravelRequestServiceImpl.java
src/main/java/com/kh/ti/travelRequest/model/vo/TravelRequest.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/views/travelRequest/request.jsp

1. 의뢰글 조회기능 구현중(조회 구현/jsp파일에 출력만 하면됨)
2. PageInfo클래스 toString메소드 추가

의뢰글 조회 기능 구현중/PageInfo클래스 toString추가

---

src/main/java/com/kh/ti/travelRequest/controller/TravelRequestController.java
src/main/java/com/kh/ti/travelRequest/model/dao/TravelRequestDao.java
src/main/java/com/kh/ti/travelRequest/model/dao/TravelRequestDaoImpl.java
src/main/java/com/kh/ti/travelRequest/model/service/TravelRequestService.java
src/main/java/com/kh/ti/travelRequest/model/service/TravelRequestServiceImpl.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/views/travelRequest/requestDetail.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestStart.jsp
src/main/webapp/WEB-INF/views/travelRequest/travelRequest.jsp

1. 의뢰글 전체조회 구현(페이징처리)
2. 의뢰글 상세조회 구현
3. 설계해주기 기능 구현중

의뢰글 전체조회/상세조회 구현/페이징처리 완료/설계해주기 기능 구현중

---

.settings/org.eclipse.wst.common.project.facet.core.xml
src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/java/com/kh/ti/travel/model/vo/Country.java
src/main/java/com/kh/ti/travel/model/vo/Travel.java
src/main/resources/mappers/travel-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/config/travel-servlet.xml
src/main/webapp/WEB-INF/views/common/mainNav.jsp
src/main/webapp/WEB-INF/views/travel/newTravelModal.jsp
src/main/webapp/WEB-INF/views/travel/travelEditor.jsp
src/main/webapp/WEB-INF/views/travel/travelInfoModal.jsp

mainNav 수정 - 모달 연결부분
mybatis-config.xml수정 - typealias 추가

(민) 새일정작성 모달수정 - 국가, 도시데이터 조회

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/travelRequest/model/vo/PlanDay.java
src/main/java/com/kh/ti/travelRequest/model/vo/PlanPlace.java
src/main/java/com/kh/ti/travelRequest/model/vo/TravelRequestPlan.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/views/travelRequest/request.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestStart.jsp

설계해주기 기능 구현중

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/travelRequest/model/vo/PlanDay.java
src/main/java/com/kh/ti/travelRequest/model/vo/PlanDayList.java
src/main/webapp/WEB-INF/views/travelRequest/requestStart.jsp

설계해주기 기능구현중

---

src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/resources/mappers/travel-mapper.xml
src/main/webapp/WEB-INF/views/travel/travelEditor.jsp
src/main/webapp/WEB-INF/views/travel/travelInfoModal.jsp

일정작성완료시 포트쪽으로 데이터 넘기는 것까지 완료/
type은 뭘로 넘겨야 하는지 몰라서 일단 "travel"로 넘김(travelController 118번 라인)
원하는대로 바꾸셔도 됩니당~

(민)일정 정보수정및 일정작성완료 기능 완성

---

src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/java/com/kh/ti/travel/model/vo/TrvDay.java
src/main/java/com/kh/ti/travel/model/vo/TrvSchedule.java
src/main/resources/mappers/travel-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/travel/newScheduleModal.jsp
src/main/webapp/WEB-INF/views/travel/scheduleEditor.jsp

mybatis-config에  TrvSch alias추가

(민) 상세일정 insert 기능

---

src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/java/com/kh/ti/travel/model/vo/TrvCost.java
src/main/java/com/kh/ti/travel/model/vo/TrvDay.java
src/main/java/com/kh/ti/travel/model/vo/TrvSchedule.java
src/main/resources/mappers/travel-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/travel/newScheduleModal.jsp
src/main/webapp/WEB-INF/views/travel/scheduleEditor.jsp

mybatis-config alias 추가 (place는 db 고치고나서 해야해서 주석으로 해놈)

(민) 상세일정 작성, 조회, 삭제 기능 완성

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDao.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDaoImpl.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestService.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestServiceImpl.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/travelRequest/requestStart.jsp

설계해주기 기능 완료

---

src/main/java/com/kh/ti/point/controller/PointController.java
src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/java/com/kh/ti/travel/model/vo/Place.java
src/main/java/com/kh/ti/travel/model/vo/Travel.java
src/main/java/com/kh/ti/travel/model/vo/TrvCost.java
src/main/java/com/kh/ti/travel/model/vo/TrvTag.java
src/main/resources/mappers/travel-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/travel/allSchedule.jsp
src/main/webapp/WEB-INF/views/travel/detailEditor.jsp
src/main/webapp/WEB-INF/views/travel/myTravel.jsp
src/main/webapp/WEB-INF/views/travel/newScheduleModal.jsp
src/main/webapp/WEB-INF/views/travel/newTravelModal.jsp
src/main/webapp/WEB-INF/views/travel/scheduleEditor.jsp
src/main/webapp/WEB-INF/views/travel/scheduleInfoModal.jsp
src/main/webapp/WEB-INF/views/travel/travelEditor.jsp
src/main/webapp/resources/js/travel/travel.js

(민) 상세일정 수정/삭제 기능, 여행테마 선택 기능, 마이페이지 나의 여행일정 조회 기능, 여행일정에 로그인 연결

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDao.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDaoImpl.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestService.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestServiceImpl.java
src/main/java/com/kh/ti/travelRequest/controller/TravelRequestController.java
src/main/java/com/kh/ti/travelRequest/model/vo/TravelRequestPlan.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/views/travelRequest/requestDetail.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestStart.jsp
src/main/webapp/WEB-INF/views/travelRequest/travelRequest.jsp

설계글 목록조회 구현 완료(이미지 추가만 하면됨)/불러오기 기능 구현중

의뢰 상세보기 설계글 목록 조회 구현 완료/불러오기 기능 구현중

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDao.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDaoImpl.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestService.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestServiceImpl.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/views/travelRequest/travelRequestLoad.jsp

불러오기 기능 구현중

---

pom.xml
src/main/java/com/kh/ti/common/CommonUtils.java
src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/java/com/kh/ti/travel/model/vo/Travel.java
src/main/java/com/kh/ti/travel/model/vo/TrvDay.java
src/main/java/com/kh/ti/travel/model/vo/TrvSchedule.java
src/main/resources/mappers/travel-mapper.xml
src/main/webapp/WEB-INF/config/travel-servlet.xml
src/main/webapp/WEB-INF/views/travel/detailEditor.jsp
src/main/webapp/WEB-INF/views/travel/newScheduleModal.jsp
src/main/webapp/WEB-INF/views/travel/scheduleEditor.jsp
src/main/webapp/WEB-INF/views/travel/scheduleInfoModal.jsp
src/main/webapp/WEB-INF/views/travel/travelEditor.jsp

(민) 상세글 작성, 사진업로드 기능 완성

---

src/main/webapp/WEB-INF/views/travelRequest/travelRequestLoad.jsp

설계해주기(불러오기)기능 구현중

---

src/main/webapp/WEB-INF/views/travelRequest/requestDetail.jsp
src/main/webapp/WEB-INF/views/travelRequest/travelRequestLoad.jsp

설계해주기 완료(중간저장 빼고)

---

src/main/java/com/kh/ti/point/controller/PointController.java
src/main/java/com/kh/ti/point/model/dao/PointDao.java
src/main/java/com/kh/ti/point/model/dao/PointDaoImpl.java
src/main/java/com/kh/ti/point/model/service/PointService.java
src/main/java/com/kh/ti/point/model/service/PointServiceImpl.java
src/main/java/com/kh/ti/point/model/vo/Rebate.java
src/main/resources/mappers/point-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/admin/adminPoint/aPayment.jsp
src/main/webapp/WEB-INF/views/common/adminMainNav.jsp
src/main/webapp/WEB-INF/views/common/mainNav.jsp
src/main/webapp/WEB-INF/views/common/myPageHeader.jsp
src/main/webapp/WEB-INF/views/point/pointNav.jsp
src/main/webapp/WEB-INF/views/point/proceedsMain.jsp

자동 차감, 수익금 자동 증가, 포인트 자동 증가, 환급신청, 환급신청내역

수민 -adminNav, mainNav 경로수정, myPageHeader 포인트,수익금 수정, 수익금 발생내역 인서트, 포인트

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDao.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDaoImpl.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestService.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestServiceImpl.java
src/main/java/com/kh/ti/myRequest/model/vo/MyPlan.java
src/main/java/com/kh/ti/myRequest/model/vo/MyRequest.java
src/main/java/com/kh/ti/travelRequest/model/vo/TravelRequestPlan.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/travelRequest/myRequestList.jsp
src/main/webapp/WEB-INF/views/travelRequest/myRequestPlan.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestPlan.jsp

채택하기 기능 구현완료/마이페이지 나의의뢰/설계 상세보기 완료/미리작성 구현중

---

pom.xml
src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/resources/mappers/travel-mapper.xml
src/main/webapp/WEB-INF/views/travel/allSchedule.jsp

(민) 엑셀다운작업중

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/myRequest/model/dao/MyRequestDaoImpl.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestServiceImpl.java
src/main/java/com/kh/ti/travelRequest/model/vo/PlanDay.java
src/main/java/com/kh/ti/travelRequest/model/vo/PlanPlace.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/views/common/myPageHeader.jsp
src/main/webapp/WEB-INF/views/travelRequest/beforePlanDetail.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestDetail.jsp

미리작성 기존글 업데이트 기능 구현 완료

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestService.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestServiceImpl.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/views/travelRequest/beforePlanDetail.jsp
src/main/webapp/WEB-INF/views/travelRequest/beforePlanList.jsp
src/main/webapp/WEB-INF/views/travelRequest/beforePlanLoad.jsp
src/main/webapp/WEB-INF/views/travelRequest/beforePlanStart.jsp
src/main/webapp/WEB-INF/views/travelRequest/myRequestList.jsp
src/main/webapp/WEB-INF/views/travelRequest/myRequestPlan.jsp
src/main/webapp/WEB-INF/views/travelRequest/travelRequestLoad.jsp

미리작성 구현 완료

---

src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/resources/mappers/travel-mapper.xml
src/main/webapp/WEB-INF/views/common/mainNav.jsp
src/main/webapp/WEB-INF/views/travel/newTravelModal.jsp
src/main/webapp/WEB-INF/views/travelBoard/myBuyTravelList.jsp

(민) 구매한일정으로 새일정 작성 작업중

---

src/main/java/com/kh/ti/myRequest/controller/MyRequestController.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestService.java
src/main/java/com/kh/ti/myRequest/model/service/MyRequestServiceImpl.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/views/inquiry/goInquiry.jsp
src/main/webapp/WEB-INF/views/inquiry/myInquiryDetail.jsp
src/main/webapp/WEB-INF/views/inquiry/myInquiryList.jsp
src/main/webapp/WEB-INF/views/panelty/paneltyDetail.jsp
src/main/webapp/WEB-INF/views/panelty/paneltyList.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestPlan.jsp

채택하기 오류 수정 완료

---

src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/java/com/kh/ti/travel/model/vo/Travel.java
src/main/java/com/kh/ti/travel/model/vo/TrvCompany.java
src/main/resources/mappers/travel-mapper.xml
src/main/webapp/WEB-INF/views/common/myPageHeader.jsp
src/main/webapp/WEB-INF/views/travel/myTravel.jsp
src/main/webapp/WEB-INF/views/travel/travelEditor.jsp

mypageHeader에 등록한 일정 count 불러오기 기능 추가

(민) 동행추가, 삭제 기능 완료

---

src/main/java/com/kh/ti/penalty/controller/PenaltyController.java
src/main/resources/mappers/penalty-mapper.xml
src/main/webapp/WEB-INF/views/panelty/paneltyDetail.jsp

문의내역 상세조회 구현 완료

---

src/main/java/com/kh/ti/adminCallCenter/controller/AdminCallCenterController.java
src/main/java/com/kh/ti/adminCallCenter/model/dao/AdminCallCenterDaoImpl.java
src/main/java/com/kh/ti/adminCallCenter/model/service/AdminCallCenterServiceImpl.java
src/main/java/com/kh/ti/adminCallCenter/model/vo/AdminNotice.java
src/main/java/com/kh/ti/adminCallCenter/model/vo/Board.java
src/main/java/com/kh/ti/travelRequest/controller/TravelRequestController.java
src/main/java/com/kh/ti/travelRequest/model/dao/TravelRequestDao.java
src/main/java/com/kh/ti/travelRequest/model/dao/TravelRequestDaoImpl.java
src/main/java/com/kh/ti/travelRequest/model/service/TravelRequestService.java
src/main/java/com/kh/ti/travelRequest/model/service/TravelRequestServiceImpl.java
src/main/java/com/kh/ti/travelRequest/model/vo/TravelRequest.java
src/main/java/com/kh/ti/travelRequest/model/vo/TravelRequestPlan.java
src/main/resources/mappers/travelRequest-mapper.xml
src/main/webapp/WEB-INF/config/admin-servlet.xml
src/main/webapp/WEB-INF/config/callCenter-servlet.xml
src/main/webapp/WEB-INF/views/admin/callCenter/adminNoticeList.jsp
src/main/webapp/WEB-INF/views/admin/callCenter/insertNotice.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestDetail.jsp
src/main/webapp/WEB-INF/views/travelRequest/requestPlan.jsp

채택 설계글 상세보기 요청 서블릿 수정/관리자 공지,자주묻는질문 구현

채택 설계글 상세보기 요청 서블릿 수정/관리자 공지, 자주묻는질문 구현중

---

src/main/java/com/kh/ti/travel/controller/TravelController.java
src/main/java/com/kh/ti/travel/model/dao/TravelDao.java
src/main/java/com/kh/ti/travel/model/dao/TravelDaoImpl.java
src/main/java/com/kh/ti/travel/model/service/TravelService.java
src/main/java/com/kh/ti/travel/model/service/TravelServiceImpl.java
src/main/resources/mappers/travel-mapper.xml
src/main/webapp/WEB-INF/views/travel/allSchedule.jsp
src/main/webapp/WEB-INF/views/travel/costEditor.jsp
src/main/webapp/WEB-INF/views/travel/costInfoModal.jsp
src/main/webapp/WEB-INF/views/travel/detailEditor.jsp
src/main/webapp/WEB-INF/views/travel/newCostModal.jsp
src/main/webapp/WEB-INF/views/travel/newScheduleModal.jsp
src/main/webapp/WEB-INF/views/travel/newTravelModal.jsp
src/main/webapp/WEB-INF/views/travel/scheduleEditor.jsp
src/main/webapp/WEB-INF/views/travel/scheduleInfoModal.jsp
src/main/webapp/WEB-INF/views/travel/travelEditor.jsp
src/main/webapp/WEB-INF/views/travel/travelInfoModal.jsp

(민) 실시간 일정공유 기능 완성
